#!/usr/bin/env node
/**
 * Interactive Setup Wizard for New Clients
 * Creates tenant configuration based on user prompts
 */

import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import {
  generateTheme,
  generateSubdomain,
  getDefaultServices,
  getTaglineTemplate,
  type IndustryType,
  type AestheticStyle,
} from '../src/design-system/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Colors for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  blue: '\x1b[34m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
};

function log(message: string, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function header(message: string) {
  log(`\n${'='.repeat(60)}`, colors.cyan);
  log(message, colors.bright + colors.cyan);
  log('='.repeat(60), colors.cyan);
  log('');
}

function question(rl: readline.Interface, prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(`${colors.blue}${prompt}${colors.reset} `, resolve);
  });
}

function select(
  rl: readline.Interface,
  prompt: string,
  options: string[]
): Promise<string> {
  return new Promise((resolve) => {
    log(`\n${prompt}`, colors.blue);
    options.forEach((opt, idx) => {
      log(`  ${idx + 1}. ${opt}`);
    });
    rl.question(
      `${colors.blue}Enter number (1-${options.length}): ${colors.reset}`,
      (answer) => {
        const index = parseInt(answer) - 1;
        if (index >= 0 && index < options.length) {
          resolve(options[index]);
        } else {
          log('Invalid selection, using first option', colors.yellow);
          resolve(options[0]);
        }
      }
    );
  });
}

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    header('🚀 New Client Setup Wizard');
    log('This wizard will help you set up a new tenant in 5 minutes!\n');

    // Step 1: Business Name
    const businessName = await question(rl, '1. Business Name:');
    if (!businessName) {
      log('Business name is required!', colors.yellow);
      rl.close();
      return;
    }

    // Step 2: Industry
    const industries: IndustryType[] = [
      'healthcare',
      'retail',
      'professional',
      'hospitality',
      'fitness',
      'beauty',
      'education',
      'technology',
      'other',
    ];
    const industry = (await select(
      rl,
      '2. Select Industry:',
      industries
    )) as IndustryType;

    // Step 3: Aesthetic
    const aesthetics: AestheticStyle[] = [
      'modern',
      'elegant',
      'minimalist',
      'bold',
    ];
    const aesthetic = (await select(
      rl,
      '3. Select Design Aesthetic:',
      aesthetics
    )) as AestheticStyle;

    // Step 4: Domain
    const suggestedDomain = `${generateSubdomain(businessName)}.com`;
    log(`\n4. Domain (suggested: ${suggestedDomain})`, colors.blue);
    const domain =
      (await question(rl, `   Press Enter to use ${suggestedDomain} or type custom:`)) ||
      suggestedDomain;

    // Step 5: Optional primary color
    log('\n5. Custom Primary Color (optional)', colors.blue);
    const primaryColor = await question(rl, '   Enter hex color (e.g., #FF6B6B) or press Enter to skip:');

    rl.close();

    // Generate configuration
    header('📝 Generating Configuration...');

    const tenantId = generateSubdomain(businessName);
    const theme = generateTheme({
      businessName,
      industry,
      aesthetic,
      domain,
      primaryColor: primaryColor || undefined,
    });

    // Create tenant directories
    const tenantsDir = path.join(__dirname, '../src/tenants', tenantId);
    if (!fs.existsSync(tenantsDir)) {
      fs.mkdirSync(tenantsDir, { recursive: true });
    }

    // Create theme config file
    const themeConfigPath = path.join(tenantsDir, 'theme.config.ts');
    const themeConfigContent = `/**
 * Theme Configuration for ${businessName}
 * Auto-generated by setup wizard
 */

import type { TenantTheme } from '../../core/types/tenant.types';

export const theme: TenantTheme = ${JSON.stringify(theme, null, 2)};
`;

    fs.writeFileSync(themeConfigPath, themeConfigContent);
    log(`✓ Created ${themeConfigPath}`, colors.green);

    // Create content config file
    const contentConfigPath = path.join(tenantsDir, 'content.config.ts');
    const defaultServices = getDefaultServices(industry);
    const tagline = getTaglineTemplate(industry);

    const contentConfigContent = `/**
 * Content Configuration for ${businessName}
 * Auto-generated by setup wizard - CUSTOMIZE THIS FILE
 */

import type { TenantContent } from '../../core/types/tenant.types';

export const content: TenantContent = {
  name: '${businessName}',
  tagline: '${tagline}',
  bio: \`Welcome to ${businessName}! We provide exceptional ${industry} services tailored to your needs.\`,
  shortBio: \`Professional ${industry} services\`,
  
  services: [
${defaultServices
  .map(
    (service, idx) => `    {
      id: 'service-${idx + 1}',
      name: '${service}',
      description: 'Description for ${service}',
      duration: '60 minutes',
      priceDisplay: 'Contact for pricing',
    }`
  )
  .join(',\n')}
  ],
  
  pricing: {
    hourly: 100,
    currency: 'USD',
    displayHourly: true,
  },
  
  contact: {
    email: 'contact@${domain}',
    phone: '+1234567890',
    phoneDisplay: '(123) 456-7890',
    availableHours: '9 AM - 5 PM EST',
  },
  
  availability: {
    location: 'Your City, State',
    willingToTravel: false,
  },
  
  seo: {
    title: '${businessName} - ${tagline}',
    description: \`Professional ${industry} services from ${businessName}\`,
    keywords: ['${industry}', 'services', businessName.toLowerCase()],
  },
};
`;

    fs.writeFileSync(contentConfigPath, contentConfigContent);
    log(`✓ Created ${contentConfigPath}`, colors.green);

    // Create photos config file
    const photosConfigPath = path.join(tenantsDir, 'photos.config.ts');
    const photosConfigContent = `/**
 * Photos Configuration for ${businessName}
 * Auto-generated by setup wizard - ADD YOUR PHOTOS HERE
 */

import type { TenantPhotos } from '../../core/types/tenant.types';

export const photos: TenantPhotos = {
  hero: {
    control: {
      url: '/images/placeholder-hero.jpg',
      alt: '${businessName} - Hero Image',
    },
  },
  gallery: [
    {
      id: 1,
      url: '/images/placeholder-1.jpg',
      alt: '${businessName} - Gallery Image 1',
    },
    {
      id: 2,
      url: '/images/placeholder-2.jpg',
      alt: '${businessName} - Gallery Image 2',
    },
    {
      id: 3,
      url: '/images/placeholder-3.jpg',
      alt: '${businessName} - Gallery Image 3',
    },
  ],
};
`;

    fs.writeFileSync(photosConfigPath, photosConfigContent);
    log(`✓ Created ${photosConfigPath}`, colors.green);

    // Create tenant index file
    const indexPath = path.join(tenantsDir, 'index.ts');
    const indexContent = `/**
 * Tenant Configuration for ${businessName}
 * Tenant ID: ${tenantId}
 */

import { theme } from './theme.config';
import { content } from './content.config';
import { photos } from './photos.config';
import type { TenantConfig } from '../../core/types/tenant.types';

export const ${tenantId.replace(/-/g, '_')}Config: TenantConfig = {
  id: '${tenantId}',
  subdomain: '${tenantId}',
  theme,
  content,
  photos,
  status: 'preview',
  customDomain: '${domain}',
  name: '${businessName}',
  features: {
    bookingEnabled: true,
    galleryEnabled: true,
    blogEnabled: false,
    reviewsEnabled: true,
    chatEnabled: false,
  },
};
`;

    fs.writeFileSync(indexPath, indexContent);
    log(`✓ Created ${indexPath}`, colors.green);

    // Update package.json name
    const packageJsonPath = path.join(__dirname, '../package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
    packageJson.name = `${tenantId}-booking-platform`;
    fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
    log(`✓ Updated package.json`, colors.green);

    // Success message
    header('✅ Setup Complete!');
    log(`Tenant ID: ${tenantId}`, colors.bright);
    log(`Domain: ${domain}`, colors.bright);
    log(`Industry: ${industry}`, colors.bright);
    log(`Aesthetic: ${aesthetic}\n`, colors.bright);

    log('Next Steps:', colors.cyan);
    log('1. Review and customize the generated config files:', colors.yellow);
    log(`   - src/tenants/${tenantId}/content.config.ts`);
    log(`   - src/tenants/${tenantId}/photos.config.ts`);
    log('2. Add your actual photos to the public/images/ directory');
    log('3. Update the TenantProvider to recognize your domain');
    log('4. Run: npm run dev');
    log('5. Test at: http://localhost:5173\n');

    log('💡 Pro Tip:', colors.green);
    log('Tell Copilot: "Fill in content for ${businessName} in ${industry} industry"');
    log('Copilot can help you customize the content with industry-specific details!\n');
  } catch (error) {
    console.error('Error during setup:', error);
    rl.close();
    process.exit(1);
  }
}

// Run the wizard
main();
